### ISSUE TITLE
Question about moving a container

### ISSUE THREAD

**Issue by ApolloX939** [TurkeyMcMac/area_containers#1]
Is there a way you can move a container?

(That is without needing to remove all nodes and such from the container)

In a local game I build a fancy mesecons system inside a container but I wanted to move the container to a new base I am constructing.

Didn't know if you had thought of ways to support this. (For the move operation I'd be tempted to have a separate tool for moving/destroying etc)

**Comment by TurkeyMcMac** [comment]
The mod won't be able to support picking up a container then placing it elsewhere. This is because containers need to free the resources associated with them. Once they are converted into items, the items can be destroyed without any notice, giving no opportunity to clean things up.

However, containers do support being moved as long as they are are placed in a new location immediately after being destroyed. For example, they can be moved using pistons. I actually have a mod that can be used to move containers and other nodes, but it can only move them one node length at a time: https://github.com/TurkeyMcMac/shifter_tool/

I could also add a dedicated tool for moving containers. The user would select a container node then select a position to move it to, at which point the node would teleport there. Maybe this tool could even be put in a separate mod and made able to move all nodes. I might work on this later. If you have the time, it probably wouldn't be too hard to implement as a separate mod, basing the movement code on this code from `mesecons_mvps`: https://github.com/minetest-mods/mesecons/blob/db5879706d04d3480bc4863ce0c03fa73e5f10c7/mesecons_mvps/init.lua#L211

**Comment by ApolloX939** [comment]
Well I was kind of thinking the move tool could teleport the block. (It looks like the shifter tool you have can work till then)

I will look into the mesecons_mvps code but you look as though you already have so perhaps you'd do a bit better at getting it to work.

**Comment by ApolloX939** [comment]
I am working on updating your [shifter_tool](https://github.com/TurkeyMcMac/shifter_tool/) mod.

Just letting you know I have looked into it and have an idea as to how to do some of this stuff.

**Comment by TurkeyMcMac** [comment]
By the way, it looks like your teleportation code may be calling add_node before remove_node (from a quick skim.) Area containers will only move properly if remove is called before add.

**Comment by ApolloX939** [comment]
Ah ha, okay, well on my progress to branch off so the teleport code isn't a part of shifter_tool I will re-arrange  the calls.

**Comment by ApolloX939** [comment]
[![ContentDB](https://content.minetest.net/packages/ApolloX/teleporter_tool/shields/title/)](https://content.minetest.net/packages/ApolloX/teleporter_tool/)
